-- Promotes answer files (unattend.xml) from a free-typed R2 key on the OS
-- profile form to a first-class catalog entity - a technician can now only
-- pick one that actually exists, generated by the admin UI's wizard.
CREATE TABLE answer_files (
  id TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  r2_key TEXT NOT NULL,
  options_json TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
