// Generates a Windows unattend.xml ("answer file") matching the working
// structure of boot/profiles/*/autounattend.xml, so a technician never has
// to hand-author XML or use the CLI upload script.
//
// Deliberately omits the <ImageInstall>/<InstallFrom> WIM-index block those
// checked-in templates carry - tracing through DeployGui.ps1 confirms the
// actual image index applied comes from the OS profile's own "Image index"
// field via `dism /Apply-Image /Index:N`, not from anything parsed out of
// this file. That block only matters for a Setup.exe-driven install, which
// this system doesn't use, so including it would just be one more "what is
// this for" mystery field with no effect.
//
// WIN-REIMAGED is a placeholder DeployGui.ps1 always substitutes with the
// technician-entered hostname before writing this file to disk - keep it
// exactly as-is.
const WORKER_BASE = "https://api.osd.xcet.uk";

export interface AnswerFileOptions {
  uiLanguage: string;
  productKey?: string;
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function generateAnswerFile(options: AnswerFileOptions): string {
  const uiLanguage = escapeXml(options.uiLanguage.trim() || "en-US");
  const productKeyBlock = options.productKey?.trim()
    ? `\n      <ProductKey>\n        <Key>${escapeXml(options.productKey.trim())}</Key>\n      </ProductKey>`
    : "";

  return `<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by the W.I.P.E admin UI's answer-file creator. The image index
  applied comes from this OS profile's own "Image index" field (DeployGui.ps1
  runs dism /Apply-Image /Index:N directly) - this file only covers the
  windowsPE UI language and the specialize/oobeSystem passes.
-->
<unattend xmlns="urn:schemas-microsoft-com:unattend">
  <settings pass="windowsPE">
    <component name="Microsoft-Windows-International-Core-WinPE" processorArchitecture="amd64"
               publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <SetupUILanguage>
        <UILanguage>${uiLanguage}</UILanguage>
      </SetupUILanguage>
      <UILanguage>${uiLanguage}</UILanguage>
    </component>
  </settings>

  <settings pass="specialize">
    <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64"
               publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">${productKeyBlock}
      <!-- WIN-REIMAGED is a placeholder DeployGui.ps1 always replaces with
           the technician-entered hostname before writing this file to disk. -->
      <ComputerName>WIN-REIMAGED</ComputerName>
    </component>
  </settings>

  <settings pass="oobeSystem">
    <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64"
               publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <FirstLogonCommands>
        <SynchronousCommand>
          <Order>1</Order>
          <CommandLine>powershell -NoProfile -Command "$mac=(Get-NetAdapter | Select-Object -First 1 -ExpandProperty MacAddress).ToLower().Replace('-',':'); Invoke-RestMethod -Method Patch -Uri (\\"${WORKER_BASE}/api/jobs/by-mac/$mac\\") -ContentType 'application/json' -Body '{\\"status\\":\\"complete\\"}'"</CommandLine>
          <Description>Phone home to os-deployment-worker</Description>
        </SynchronousCommand>
        <SynchronousCommand>
          <Order>2</Order>
          <CommandLine>powershell -NoProfile -Command "New-Item -ItemType Directory -Force -Path C:\\Windows\\Setup\\Scripts | Out-Null; Invoke-WebRequest -Uri '${WORKER_BASE}/images/winpe/PostAction.ps1' -OutFile 'C:\\Windows\\Setup\\Scripts\\PostAction.ps1'; if (-not (Test-Path 'C:\\Windows\\Setup\\Scripts\\post-action.json')) { '{\\"domainJoin\\":false,\\"steps\\":[]}' | Set-Content 'C:\\Windows\\Setup\\Scripts\\post-action.json' }"</CommandLine>
          <Description>Fetch the post-action script; seed a no-domain-join/no-steps default in case DeployGui.ps1 didn't already write one</Description>
        </SynchronousCommand>
        <SynchronousCommand>
          <Order>3</Order>
          <CommandLine>powershell -NoProfile -ExecutionPolicy Bypass -File C:\\Windows\\Setup\\Scripts\\PostAction.ps1</CommandLine>
          <Description>Run the post-imaging action (domain join, then task sequence steps)</Description>
        </SynchronousCommand>
      </FirstLogonCommands>
    </component>
  </settings>
</unattend>
`;
}
