// Generates a Windows unattend.xml ("answer file") matching the working
// structure of boot/profiles/*/autounattend.xml, so a technician never has
// to hand-author XML or use the CLI upload script.
//
// Deliberately omits two blocks those checked-in templates carry (or that a
// "kitchen sink" answer file would normally include), because tracing
// through DeployGui.ps1 confirms this system doesn't need them and they'd
// just be more "what is this for" dead weight:
//   - <ImageInstall>/<InstallFrom> (WIM index) - DeployGui.ps1 runs
//     `dism /Apply-Image /Index:N` directly from the OS profile's own
//     "Image index" field, never anything parsed out of this file.
//   - <DiskConfiguration> (partitioning) - DeployGui.ps1 partitions the disk
//     itself via a diskpart script before DISM ever touches the WIM.
// Also deliberately excludes local-account/AutoLogon creation: unlike
// domain-join (which DeployGui.ps1 writes straight to the target disk and
// PostAction.ps1 scrubs immediately after use), anything in this file is a
// plaintext R2 object that outlives the deployment - not a place to put an
// account password.
//
// WIN-REIMAGED is a placeholder DeployGui.ps1 always substitutes with the
// technician-entered hostname before writing this file to disk - keep it
// exactly as-is.
const WORKER_BASE = "https://api.osd.xcet.uk";

export interface AnswerFileOptions {
  uiLanguage: string;
  timeZone: string;
  registeredOwner: string;
  registeredOrganization: string;
  productKey: string;
  skipOobe: boolean;
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function optionalElement(tag: string, value: string): string {
  return value.trim() ? `\n      <${tag}>${escapeXml(value.trim())}</${tag}>` : "";
}

export function generateAnswerFile(options: AnswerFileOptions): string {
  const uiLanguage = escapeXml(options.uiLanguage.trim() || "en-US");
  const productKeyBlock = options.productKey.trim()
    ? `\n      <ProductKey>\n        <Key>${escapeXml(options.productKey.trim())}</Key>\n      </ProductKey>`
    : "";
  const timeZoneBlock = optionalElement("TimeZone", options.timeZone);
  const ownerBlock = optionalElement("RegisteredOwner", options.registeredOwner);
  const orgBlock = optionalElement("RegisteredOrganization", options.registeredOrganization);
  const oobeBlock = options.skipOobe
    ? `
      <OOBE>
        <HideEULAPage>true</HideEULAPage>
        <HideOEMRegistrationPage>true</HideOEMRegistrationPage>
        <HideOnlineAccountScreens>true</HideOnlineAccountScreens>
        <HideWirelessSetupInOOBE>true</HideWirelessSetupInOOBE>
        <NetworkLocation>Work</NetworkLocation>
        <ProtectYourPC>3</ProtectYourPC>
        <SkipUserOOBE>true</SkipUserOOBE>
        <SkipMachineOOBE>true</SkipMachineOOBE>
      </OOBE>`
    : "";

  return `<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by the W.I.P.E admin UI's answer-file wizard. The image index
  applied comes from the OS profile's own "Image index" field, and disk
  partitioning is handled by DeployGui.ps1 itself - this file only covers
  the windowsPE UI language and the specialize/oobeSystem passes.
-->
<unattend xmlns="urn:schemas-microsoft-com:unattend">
  <settings pass="windowsPE">
    <component name="Microsoft-Windows-International-Core-WinPE" processorArchitecture="amd64"
               publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <SetupUILanguage>
        <UILanguage>${uiLanguage}</UILanguage>
      </SetupUILanguage>
      <UILanguage>${uiLanguage}</UILanguage>
    </component>
  </settings>

  <settings pass="specialize">
    <component name="Microsoft-Windows-International-Core" processorArchitecture="amd64"
               publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <InputLocale>${uiLanguage}</InputLocale>
      <SystemLocale>${uiLanguage}</SystemLocale>
      <UILanguage>${uiLanguage}</UILanguage>
      <UserLocale>${uiLanguage}</UserLocale>
    </component>
    <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64"
               publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">${productKeyBlock}${timeZoneBlock}${ownerBlock}${orgBlock}
      <!-- WIN-REIMAGED is a placeholder DeployGui.ps1 always replaces with
           the technician-entered hostname before writing this file to disk. -->
      <ComputerName>WIN-REIMAGED</ComputerName>
    </component>
  </settings>

  <settings pass="oobeSystem">
    <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64"
               publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">${oobeBlock}
      <FirstLogonCommands>
        <!-- Deliberately does NOT run PostAction.ps1 directly - Microsoft's
             own docs now say FirstLogonCommands entries "are all started at
             the same time, and no longer wait for the previous command to
             finish" on current Windows, despite the Order element below.
             This one entry only does fast, order-independent setup (fetch/
             seed files, write one registry value) and seeds a RunOnce entry
             instead - RunOnce fires once, right as the first interactive
             desktop session starts, which is what lets PostAction.ps1 show
             a real GUI instead of running invisibly before the desktop even
             appears. The "!" prefix on the value name defers its deletion
             until after the command exits, so if PostAction.ps1's own
             domain-join reboot kills the process partway through, Windows
             re-runs it at the next logon instead of losing the rest of the
             work - see boot/winpe/PostAction.ps1 for the resume logic. -->
        <SynchronousCommand>
          <Order>1</Order>
          <CommandLine>powershell -NoProfile -Command "New-Item -ItemType Directory -Force -Path C:\\Windows\\Setup\\Scripts | Out-Null; Invoke-WebRequest -Uri '${WORKER_BASE}/images/winpe/PostAction.ps1' -OutFile 'C:\\Windows\\Setup\\Scripts\\PostAction.ps1'; if (-not (Test-Path 'C:\\Windows\\Setup\\Scripts\\post-action.json')) { '{\\"domainJoin\\":false,\\"steps\\":[]}' | Set-Content 'C:\\Windows\\Setup\\Scripts\\post-action.json' }; New-ItemProperty -Path 'HKLM:\\Software\\Microsoft\\Windows\\CurrentVersion\\RunOnce' -Name '!PostAction' -Value 'powershell -NoProfile -ExecutionPolicy Bypass -File C:\\Windows\\Setup\\Scripts\\PostAction.ps1' -PropertyType String -Force | Out-Null"</CommandLine>
          <Description>Fetch the post-action script and seed defaults, then queue it to run via RunOnce once the desktop is reached</Description>
        </SynchronousCommand>
      </FirstLogonCommands>
    </component>
  </settings>
</unattend>
`;
}
